---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "🦄 Developer Experience 🔥"
subtitle: "Red Hat Open Innovation Labs"
# logo: "https://avatars1.githubusercontent.com/u/19174470?s=200&v=4"
logo: "https://www.redhat.com/cms/managed-files/RHOIL_LogoBadge_RGB_Default.svg"
# icon: "fas fa-skull-crossbones" Optional icon
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.

# Optional message
# message:
#   # url: https://....
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !" 
#   content: "This is a dummy homepage demo. Find more information on github.com/bastienwirtz/homer"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Ubiquitous Journey"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/ubiquitous-journey"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Open Management Portal"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/open-management-portal"
  - name: "Helm Charts"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/helm-charts"
  - name: "DO500"
    icon: "fab fa-github"
    url: "https://github.com/rht-labs/enablement-docs"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

      # - name: ""
      #   logo: ""
      #   subtitle: ""
      #   tag: ""
      #   url: ""
      #   target: '_blank'

services:
  - name: "Automation"
    icon: "fas fa-code-branch"
    items:
      - logo: images/jenkins.jpeg
        name: Jenkins
        subtitle: Continuous integration server
        tag: ci
        target: _blank
        url: https://jenkins-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: https://argoproj.github.io/argo-cd/assets/logo.png
        name: ArgoCD
        subtitle: Git driven Operations
        tag: ci, gitops
        target: _blank
        url: https://argocd-server-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: https://github.com/redhat-developer/codeready-workspaces/raw/master/product/branding/CodeReady.png
        name: CodeReady Workspaces
        subtitle: Cloud hosted dev stack
        tag: dev
        target: _blank
        url: https://codeready-crw.apps.hivec.sandbox1604.opentlc.com/dashboard
      - logo: https://user-images.githubusercontent.com/7955995/29498304-ee71d418-85c6-11e7-9f95-e87a4439ed3c.png
        name: Nexus
        subtitle: Software artifact repository
        tag: dev, artifacts
        target: _blank
        url: https://nexus-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: https://www.sonarqube.org/images/downloads/picto.svg
        name: SonarQube
        subtitle: Software quality tooling
        tag: testing, quality
        target: _blank
        url: http://sonarqube-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: https://gitlab.com/okj8/zalenium/-/avatar
        name: Zalenium
        subtitle: Browser testing tools
        tag: testing, browser
        target: _blank
        url: http://zalenium-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: images/tekton.png
        name: Tekton
        subtitle: Kuberntes native pipelines
        tag: pipelines
        target: _blank
        url: 'https://console-openshift-console.apps.hivec.sandbox1604.opentlc.com/k8s/ns/labs-ci-cd/tekton.dev~v1alpha1~Pipeline'
      - logo: images/vault.png
        name: HashiCorp Vault
        subtitle: Store secrets and tokens securely
        tag: secrets
        target: _blank
        url: https://vault-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - logo: images/grafana.png
        name: Grafana
        subtitle: Metric analytics & dashboards
        tag: metrics, dashboard
        url: http://argocd-grafana-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
        target: _blank
      - logo: https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2017/11/prometheus_logo.png
        name: Prometheus
        subtitle: Collect Mertics
        tag: metrics
        target: _blank
        url: http://argocd-prometheus-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: images/hoverfly.jpeg
        name: Hoverfly
        subtitle: API Simulations and Testing
        tag: api
        target: _blank
        url: https://hoverfly-hoverfly-admin-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: images/pact.png
        name: Pact
        subtitle: Consumer Driven Contract Testing
        tag: api
        target: _blank
        url: http://pact-broker-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com/
  - name: "Project Management"
    icon: "fas fa-tasks"
    items:
      - logo: https://avatars0.githubusercontent.com/u/11725037?s=200&v=4
        name: Wekan
        subtitle: Wekan Tasks
        tag: kanban
        target: _blank
        url: https://wekan-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com/
      - logo: https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_0b2e8ea823612a322cf779c35039d756/mattermost.png
        name: Mattermost
        subtitle: Cluster hosted Chat app
        tag: chat
        target: _blank
        url: https://mattermost-team-edition-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: images/etherpad.jpeg
        name: Etherpad
        subtitle: Collaborative text pad
        tag: write, text
        target: _blank
        url: https://etherpad-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
      - logo: images/owncloud.png
        name: Owncloud
        subtitle: Share your documents
        tag: sharing, documents
        target: _blank
        url: https://owncloud.apps.hivec.sandbox1604.opentlc.com
